import streamlit as st
import pandas as pd

# Load the CSV data
file_path = 'Spring Intrasquads MASTER.csv'
data = pd.read_csv(file_path, low_memory=False)

# Streamlit app
st.set_page_config(page_title="Post-Game Hitter Report", layout="centered")

# Sidebar for selecting date
selected_date = st.sidebar.selectbox("Select a Date", data['Date'].unique())
data_by_date = data[data['Date'] == selected_date]

# Sidebar for selecting batter
batter_name = st.sidebar.selectbox("Select a Batter", data_by_date['Batter'].unique())

# Filter data for the selected batter
batter_data = data_by_date[data_by_date['Batter'] == batter_name]

# Extract today's date from the "Date" column in the CSV
today_date = batter_data['Date'].iloc[0] if not batter_data.empty else "Unknown Date"

# Calculate values for the game stats table
PA = batter_data[batter_data['PitchofPA'] == 1].shape[0]
H = batter_data[batter_data['PlayResult'].isin(["Single", "Double", "Triple", "HomeRun"])].shape[0]
Doubles = batter_data[batter_data['PlayResult'] == "Double"].shape[0]
Triples = batter_data[batter_data['PlayResult'] == "Triple"].shape[0]
HR = batter_data[batter_data['PlayResult'] == "HomeRun"].shape[0]
TB = (batter_data['PlayResult'] == "Single").sum() * 1 + \
     (batter_data['PlayResult'] == "Double").sum() * 2 + \
     (batter_data['PlayResult'] == "Triple").sum() * 3 + \
     (batter_data['PlayResult'] == "HomeRun").sum() * 4
RBI = batter_data['RunsScored'].sum()
BB = batter_data[batter_data['KorBB'] == "Walk"].shape[0]
HBP = batter_data[batter_data['PitchCall'] == "HitByPitch"].shape[0]
SO = batter_data[batter_data['KorBB'] == "Strikeout"].shape[0]
EVMax = batter_data['ExitSpeed'].max()
EVAvg = batter_data['ExitSpeed'].mean()

# Define game stats for the table
game_stats = pd.DataFrame({
    "PA": [PA], "H": [H], "2B": [Doubles], "3B": [Triples], "HR": [HR],
    "TB": [TB], "RBI": [RBI], "BB": [BB], "HBP": [HBP], "SO": [SO],
    "EVMax": [round(EVMax, 1) if pd.notnull(EVMax) else None],
    "EVAvg": [round(EVAvg, 1) if pd.notnull(EVAvg) else None]
})

# Define plate appearances table dynamically
plate_appearances = []

# Group data by plate appearances dynamically using groupby
plate_appearance_groups = batter_data.groupby((batter_data['PitchofPA'] == 1).cumsum())

for pa_number, pa_data in enumerate(plate_appearance_groups, start=1):
    pa_id, pa_rows = pa_data
    if pa_rows.empty:
        plate_appearances.append([pa_number, "NA", "NA", "NA", 0, "NA", "NA", "NA", "NA", "NA"])
        continue

    inning = pa_rows['Inning'].iloc[0] if not pa_rows['Inning'].isnull().all() else "NA"
    pitcher = pa_rows['Pitcher'].iloc[0] if not pa_rows['Pitcher'].isnull().all() else "NA"

    # Determine result
    result_candidates = [
        ("KorBB", pa_rows[pa_rows['KorBB'].isin(["Strikeout", "Walk"])]),
        ("PlayResult", pa_rows[pa_rows['PlayResult'].isin(["Out", "Single", "Double", "Triple", "HomeRun", "Sacrifice"])]),
        ("PitchCall", pa_rows[pa_rows['PitchCall'] == "HitByPitch"])
    ]
    result = "NA"
    for column, candidates in result_candidates:
        if not candidates.empty:
            result = candidates.iloc[0][column]
            break

    # Runs scored
    runs = pa_rows['RunsScored'].sum()

    # Last pitch data
    last_pitch = pa_rows.iloc[-1]
    pitch = last_pitch['TaggedPitchType'] if pd.notnull(last_pitch['TaggedPitchType']) else "NA"
    pitch_speed = last_pitch['RelSpeed'] if pd.notnull(last_pitch['RelSpeed']) else "NA"
    ev = last_pitch['ExitSpeed'] if pd.notnull(last_pitch['ExitSpeed']) else "NA"
    la = last_pitch['Angle'] if pd.notnull(last_pitch['Angle']) else "NA"
    distance = last_pitch['Distance'] if pd.notnull(last_pitch['Distance']) else "NA"

    plate_appearances.append([pa_number, inning, pitcher, result, runs, pitch, pitch_speed, ev, la, distance])

plate_appearances_df = pd.DataFrame(plate_appearances, columns=["PA #", "Inning", "Pitcher", "Result", "Runs", "Pitch", "PitchSpeed", "EV", "LA", "Distance"])

# Streamlit layout
st.title(f"Post-Game Hitter Report: {batter_name}")
st.subheader(f"Date: {selected_date}")

st.markdown("### Game Stats")
st.table(game_stats)

st.markdown("### Plate Appearances")
st.table(plate_appearances_df)

st.markdown("---")
st.markdown("*Generated by Post-Game Hitter Report App*")
